//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialWebsiteMVC5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public System.Guid CommenterID { get; set; }
        public int CommentID { get; set; }
        public string CommentContent { get; set; }
        public int PostID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Post Post { get; set; }
    }
}
